### ISSUE TITLE
Themes get reset on reload

### ISSUE THREAD

**Issue by rsp-rns** [mayank1513/nextjs-themes#8]
**Describe the bug**
Themes are getting reset on reload

**To Reproduce**
1. Deploy the site
2. Change the default dark and light themes
3. Set colorScheme to system
4. Reload the page

**Expected behavior**
On reload same themes should be there

**Additional context**
Seems like the error is because of conflict between persist middleware and shared.

**Comment by mayank1513** [comment]
I have fixed this issue. Will soon create a new release with the fix. Thanks!
